os:
  - linux
  - osx

language: generic

env:
  matrix:
    - python=2.7  CONDA_PY=27
    - python=3.4  CONDA_PY=34    
    - python=3.5  CONDA_PY=35
    - python=3.6  CONDA_PY=36
    - python=3.7  CONDA_PY=37

  global:
    - secure: "MOXTAb0t9z513Rn66D/k72Bj+8ahaawGj9gVSy3e7XZo4laA4x7gXFlKWykxN04tZtJk+98s7NjRIsZHFplqasSq2nNGqOIt99q2QNf3S0JEdUWAP98uyRELEz+jdujebN5Zo4LaxydebxH6TknHvniwqZ3tEiytcpGj391d0VBSckqTEvoyHHtZZcp19C7yDpIp0Qs/bbM+5klnHEHRLqQxh5YUzuidj2VoTYOG4XBYyQv4kf8hAXAIzvs3hEc2bXmN0C6HfAEzNtf9xoGvW9qmClVqZT1IlAaTDHwkK5smrfC/pdrsNiXAs8vak2erOBRG56e6m4k1qP9FuXUeAuWdPHDE/vJDp+9V8n61VNUxsZWFOe/340qHwkVDMwdqpDPVV424irdoK+sci2+pMsgOBi5/pDB+QXgcQxNQ4FA3z17UGg7SHsB9xNWr0kzqv61McFvUDkiNlb7orv5cCvcqvIbAjmdSupspbFqiKj95k82Cuw1z9qd84CEIA2bbyiCTZY4i6fe143T49eDgCNmU1fOM8edbdqPaeAhiIkjWtmpfnSon2CJ6JCgaUoqx2Wsdy9jS6stpllfR2quf7M/uuqFSLuq6HoWji/NIHMxdIeMN7MpYRgunYRS5Rxv0r9o+ggRG0pCJGGeTihg2TQEr2pfQjLxA2DkCXB1RrLQ="
    - secure: "YWapPXIzFc7P8dR2xTTCJxY++25OI8hvrlsQKeEu2ZrfCuYnzfDy8F+qM7z4xl4x5iEsZUQ9GmcmNLBFiAOJdcLqCUAkEVALCt7Z3UE+/GFcPybqOwBitRQcARJdkKfn56Ot3qBYxoHIZG0kkVMQl4crT0GIUWHW0nBcliCsUPOc+nl4fQArfLk8dIIO2Tu5TdTxxHnvdjGDGvV8eXX+LDhOIWMSuTiVx713IcWOeW7A/3NMBfJJsGUldL4EBVHvP8HdCRYfT3hEBBktGHL0AacowSimtsTwkVzLLFov5+WxOSTiJRA/Kcqbws7YOvYkdbbNSNKWV7hDpX6jCpYks6rOicfmz/ZIhaDuKAW2p4uMSJebN/0NUoLzcrriKfZ/LXQ/mUDh9ZW2osYwBt/zmSI2RrgT+I7uVulhU3CSBjL6w2GLhgKLmcaIVAaUJVp9W/HAtBlFek238RzyYyGanqN3zdfBfue7P6wG0JPYOHgqUlgjw0a75eFE5TkkG4NaH/W+0cPrEz1TvyxC+PCUG7nuskZgH1Ig94FTcio+rjlSsISKRPccKQ0CjCyeucIQBqWdbohwJeL7mstbTwxD57+dDITrkwQNHuE7BinfvzHWuChT8B7FJr59IPOtRNIztO8+0pRpPwx+bqSQoeFdO/2DfnYTwNZz9b3UJe8fK0U="    


before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then curl -L -o miniconda.sh http://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh; fi
  - chmod 755 miniconda.sh
  - ./miniconda.sh -b
  - export PATH=$HOME/miniconda3/bin:$PATH
  - conda update --yes conda
  - conda create --yes -n ingeotec python=$python
  - source activate ingeotec  
  - conda install --yes pip
  - pip install coverage
  - pip install coveralls
  - conda config --append channels ingeotec  
  - conda install --yes nose sparsearray cython numpy
  - python setup.py build_ext --inplace

# command to run tests
script:
  - which python
  - python --version
  - which coverage
  - if [ $python = 2.7 ]; then nosetests --verbose -exe EvoDAG; fi
  - if [ $python = 3.4 ]; then nosetests --verbose -exe EvoDAG; fi  
  - if [ $python = 3.5 ]; then nosetests --verbose -exe EvoDAG; fi
  - if [ $python = 3.7 ]; then nosetests --verbose -exe EvoDAG; fi
  - if [ $python = 3.6 ]; then coverage run setup.py nosetests; fi

after_success:
  - if [ $python = 3.6 ]; then coveralls || echo "Coveralls upload failed"; fi
  - if [ $TRAVIS_BRANCH = "master" -a $python = 3.6 ]; then python setup.py sdist; pip install twine; twine upload -u mgraffg -p $TWINE dist/*.tar.gz; fi
  - if [ $TRAVIS_BRANCH = "master" ]; then python setup.py bdist_wheel; pip install twine; twine upload -u mgraffg -p $TWINE dist/*.whl; fi  
  - if [ $TRAVIS_BRANCH = "master" ]; then source deactivate; conda install --yes pip conda-build jinja2 anaconda-client; conda build conda-recipe --quiet; fi
  - python continuous-integration/move-conda-package.py conda-recipe  
  - which binstar
  - python continuous-integration/binstar-push.py

notifications:
    email:
      recipients:
        - mario.graff@infotec.mx
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
